#!/bin/sh
## laptop
# fetch files from wiki
sudo systemctl stop firewall
sudo ifconfig enp0s25 192.168.1.2
sudo dnsmasq -p0 --enable-tftp --tftp-root=`pwd` -d --user=`whoami`

## serial port
setenv ipaddr '192.168.1.1'
setenv serverip '192.168.1.2'
tftp 0x6400000 uboot.2016.05-tld-1.goflexnet.mtd0.kwb

# DONT FUCK UP NOW
nand erase 0x0 0x100000
nand write.e 0x6400000 0x0 0x80000
# PHEW

tftp 0x6400000 openwrt-15.05.1-kirkwood-goflexnet-uImage
nand erase 0x100000 0x400000
nand write.e 0x6400000 0x100000 1a8f49

reset

# prepare partition
setenv mtdparts mtdparts=orion_nand:1M(u-boot),4M(uImage),-(rootfs)
saveenv
setenv ipaddr '192.168.1.1'
setenv serverip '192.168.1.2'

nand erase.part rootfs
ubi part rootfs
ubi create rootfs
tftp 0x6400000 openwrt-15.05.1-kirkwood-goflexnet-rootfs.ubifs
ubi write 0x6400000 rootfs 46e000

setenv bootcmd '${x_bootcmd_kernel}; setenv bootargs ${x_bootargs} ${x_bootargs_root}; ${x_bootcmd_usb}; bootm 0x6400000;'
setenv bootdelay '3'
setenv ethact 'egiga0'
setenv ethaddr '00:10:BLABLABLA'
setenv x_bootargs 'console=ttyS0,115200 mtdparts=orion_nand:1M(u-boot),4M@1M(kernel),-@5M(rootfs) rw'
setenv x_bootargs_root 'ubi.mtd=2  rootfstype=ubifs'
setenv x_bootcmd_kernel 'nand read 0x6400000 0x100000 0x400000'
setenv x_bootcmd_usb 'usb start'
setenv machid c11
saveenv
reset

# in shell
cat > /etc/dropbear/authorized_keys <<EOF
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC7HCK+TzelJp7atCbvCbvZZnXFr3cE35ioactgpIJL7BOyQM6lJ/7y24WbbrstClTuV7n0rWolDgfjx/8kVQExP3HXEAgCwV6tIcX/Ep84EXSok7QguN0ozZMCwX9CYXOEyLmqpe2KAx3ggXDyyDUr2mWs04J95CFjiR/YgOhIfM4+gVBxGtLSTyegyR3Fk7O0KFwYDjBRLi7a5TIub3UYuOvw3Dxo7bUkdhtf38Kff8LEK8PKtIku/AyDlwZ0mZT4Z7gnihSG2ezR5mLD6QXVuGhG6gW/gsqfPVRF4aZbrtJWZCp2G21wBRafpEZJ8KFHtR18JNcvsuWA1HJmFOj2K0mAY5hBvzCbXGhSzBtcGxKOmTBDTRlZ7FIFgukP/ckSgDduydFUpsv07ZRj+qY07zKp3Nhh3RuN7ZcveCo2WpaAzTuWCMPB0BMhEQvsO8I/p5YtTaw2T1poOPorBbURQwEgNrZ92kB1lL5t1t1ZB4oNeDJX5fddKLkgnLqQZWOZBTKtoq0EAVXojTDLZaA+5z20h8DU7sicDQ/VG4LWtqm9fh8iDpvt/3IHUn/HJEEnlfE1Gd+F2Q+R80yu4e1PClmuzfWjCtkPc4aY7oDxfcJqyeuRW6husAufPqNs31W6X9qXwoaBh9vRQ1erZUo46iicxbzujXIy/Hwg67X8dw== dickbutt
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQChCIEv4O+EaM5y4vBghKBMKCh+ee26SzjkrwTQHuxqA0lFwkc61HbLS0K6hZuMmD6XZY/w0ERCcKS87U9PRGbX+cwlXOhybGfdSWtwz57g27Y1Z4SGb9DXvH5q4vDFYvvWj3T9ujb1Ph+hBJgxuKBDTUqPi/3Wl+yKnIyPYTmWhpZTshOgqbCZCUAOauyTP3usymycCo8IF1rIwLRAi6phjdklvSPegxZDg3hfmcemMiCBEUTEmP1jUvOY/XCVlv21NUiwtDZ6XAAElScDFX1pLZJjcTaYwOz17o2HCtTMFnL2NN/VcFBG+midGvIhgvGXqhS/EghNQUGHlZXHKIuP
EOF

scp -r ~/r/elchos/flashing root@10.42.22.173:/
